name: 'Check'
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: 'ubuntu-22.04'
    container:
      image: 'rust:1.72-buster'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      - name: 'Install rustfmt and clippy'
        run: 'rustup component add rustfmt clippy'
      - name: 'Build application'
        run: 'cargo build'
      - name: 'Check format'
        run: 'cargo fmt --check'
      - name: 'Lint with Clippy'
        run: 'cargo clippy'
      - name: 'Run tests'
        run: 'cargo test'
